name: Deploy to Dev

on:
  push:
    branches: [ master, piyush/deployment ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -P staging

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{ secrets.aws_access_key }}
        aws_secret_key: ${{ secrets.aws_secret_key }}
        region: ap-south-1
        application_name: control-backend-dev-app
        environment_name: control-backend-dev-env
        version_label: ${{ github.sha }}
        deployment_package: target/hospitalerp.war
